// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvpezltqpphvolzgfhme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2cGV6bHRxcHBodm9semdmaG1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MTY3MzUsImV4cCI6MjA3MDQ5MjczNX0.R2EvoKf8X6EvA20jOeMLZxfFqRvtwL0VhkB0e1O9ZwE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});